name: cd

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}
      input_publish_dir: ./public
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

      - name: Release
        run: npm run release
